linters:
  enable:
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - misspell
    - revive
    - whitespace

# Per-linter settings are contained in this top-level key
linters-settings:
  gofmt:
    rewrite-rules:
      - pattern: "interface{}"
        replacement: "any"

  goimports: {}

  misspell: {}

  revive:
    enable-all-rules: false
    ignore-generated-header: true
    rules:
      - name: atomic
      - name: context-keys-type
      - name: defer
        arguments: [
            [
              # Calling 'recover' at the time a defer is registered (i.e. "defer recover()") has no effect.
              "immediate-recover",
              # Calling 'recover' outside of a deferred function has no effect
              "recover",
              # Returning values from a deferred function has no effect
              "return",
            ],
          ]
      - name: duplicated-imports
      - name: errorf
      - name: string-of-int
      - name: time-equal
      - name: unconditional-recursion
      - name: useless-break
      - name: waitgroup-by-value
